import json

response = {
    "success": True,
    "data": [
        {"Transporter": "OKHLA TRANSPORT COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "Sitara Logistics", "uniqueVehicleCount": 1},
        {"Transporter": "DVRL", "uniqueVehicleCount": 10},
        {"Transporter": "NITESH VAIDYA", "uniqueVehicleCount": 1},
        {"Transporter": "KRISHNA TRANSPORT COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "SAI DAILY SERVICES", "uniqueVehicleCount": 6},
        {"Transporter": "MOHINDER KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "MR.KISHOREBHAI D PATEL", "uniqueVehicleCount": 1},
        {"Transporter": "SALIM SHAIKH", "uniqueVehicleCount": 1},
        {"Transporter": "WANI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ARSHAD KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "ZABIULLA BN", "uniqueVehicleCount": 1},
        {"Transporter": "SARKAR LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "ASHISH PAL", "uniqueVehicleCount": 3},
        {"Transporter": "ARAB ABUBAKAR RAHIM", "uniqueVehicleCount": 2},
        {"Transporter": "KULDEEP SINGH THAKUR", "uniqueVehicleCount": 1},
        {"Transporter": "SAIKAM DHANA LAKSHMI", "uniqueVehicleCount": 1},
        {"Transporter": "R R ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE RAM TRANSPORT SERVICE", "uniqueVehicleCount": 13},
        {"Transporter": "KHODAL KRUPA ROADWAYS", "uniqueVehicleCount": 1},
        {"Transporter": "DEVANSH LOGISTICS", "uniqueVehicleCount": 18},
        {"Transporter": "KAPOOR DIESELS GARAGE PVT.LTD", "uniqueVehicleCount": 2},
        {"Transporter": "D>roy Enterprise", "uniqueVehicleCount": 3},
        {"Transporter": "PRAMOD PRAKASH DHAMALE", "uniqueVehicleCount": 2},
        {"Transporter": "CHANCHAL GOOD CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "RAJESWARI TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "ELEGANT EXPRESS COURIER", "uniqueVehicleCount": 1},
        {"Transporter": "AMELINA DA CUNHA", "uniqueVehicleCount": 1},
        {"Transporter": "N.S.TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "V.MURUGAN", "uniqueVehicleCount": 1},
        {"Transporter": "VIRENDER SINGH", "uniqueVehicleCount": 2},
        {"Transporter": "JAYASHANKAR B M", "uniqueVehicleCount": 2},
        {"Transporter": "ANIL TEMPO SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "SUNITA KUMARI GOUDA", "uniqueVehicleCount": 1},
        {"Transporter": "BABLI TOURIST SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "ASHOK KUMAR SEHRAWAT", "uniqueVehicleCount": 2},
        {"Transporter": "ADVIK TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "ANITA VITHAL JADHAV", "uniqueVehicleCount": 1},
        {"Transporter": "SHREEJI LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SRI MURUGAN TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "DEVENDRAN.M", "uniqueVehicleCount": 1},
        {"Transporter": "THILAGAM TRANSPORTS & TRAVELS", "uniqueVehicleCount": 2},
        {"Transporter": "PUTTALINGAMMA", "uniqueVehicleCount": 1},
        {"Transporter": "SREE MAN TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SHER SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "S.L.V. ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "SARKAR LOGISTIC", "uniqueVehicleCount": 1},
        {"Transporter": "SUDHIR DOHARE", "uniqueVehicleCount": 2},
        {"Transporter": "KAPOOR DIESELS GARAGE PRIVATE LIMITED", "uniqueVehicleCount": 1},
        {"Transporter": "MONANK TRANSPORT", "uniqueVehicleCount": 5},
        {"Transporter": "K LTHOMAS", "uniqueVehicleCount": 8},
        {"Transporter": "C.POOVAMMAL", "uniqueVehicleCount": 1},
        {"Transporter": "Shankar Sopan Kanse", "uniqueVehicleCount": 1},
        {"Transporter": "GOGOI ENGINEERING", "uniqueVehicleCount": 2},
        {"Transporter": "GORAKHANATH AUTO SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "MAHALYA TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "NAVNATH HULAVALE ", "uniqueVehicleCount": 1},
        {"Transporter": "MAHALAXMI TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "RAMESH TRAVELS COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "BRIGHT GLOBAL CO", "uniqueVehicleCount": 5},
        {"Transporter": "DINESH KASHINATH SABALE", "uniqueVehicleCount": 1},
        {"Transporter": "SINGH TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "VENKATESHA N", "uniqueVehicleCount": 2},
        {"Transporter": "S S KHAN TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "GYAN COLD DRINKS & TEMPO SERVICS", "uniqueVehicleCount": 1},
        {"Transporter": "AKHILESH S .YADAV", "uniqueVehicleCount": 5},
        {"Transporter": "SHRI JAI BHAWANI GOODS TRANSPORT CO", "uniqueVehicleCount": 2},
        {"Transporter": "V.GURUNATHAN", "uniqueVehicleCount": 2},
        {"Transporter": "PAUL ENTERPRISE", "uniqueVehicleCount": 1},
        {"Transporter": "BABASO VILAS MAHANGADE", "uniqueVehicleCount": 1},
        {"Transporter": "K. RAM", "uniqueVehicleCount": 1},
        {"Transporter": "MOHIT KUMAR MISHRA", "uniqueVehicleCount": 8},
        {"Transporter": "PRAVIN PRABHAKAR CHALKE", "uniqueVehicleCount": 1},
        {"Transporter": "MOHAN CHANDRA", "uniqueVehicleCount": 8},
        {"Transporter": "SANA ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "AMARNATH PARIBAHAN", "uniqueVehicleCount": 1},
        {"Transporter": "BHI CASH CONTRACTOR", "uniqueVehicleCount": 3},
        {"Transporter": "OM SAI ENTERPRISES", "uniqueVehicleCount": 3},
        {"Transporter": "VENKATARAMAPPA", "uniqueVehicleCount": 1},
        {"Transporter": "TAKE LOGISTICS SOLUTIONS", "uniqueVehicleCount": 1},
        {"Transporter": "DUMMAY ENTRY", "uniqueVehicleCount": 7},
        {"Transporter": "ABRAR ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "BHAVESH TRANSPORT SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "OMSAI CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "INTERCITY EXPRESS", "uniqueVehicleCount": 8},
        {"Transporter": "S D LOGISTIC", "uniqueVehicleCount": 2},
        {"Transporter": "SANJAY MANE", "uniqueVehicleCount": 1},
        {"Transporter": "DINESH KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "NISHA TRANSPORT & LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "ANSHU LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "RAVI GUPTA", "uniqueVehicleCount": 1},
        {"Transporter": "AJIT KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "BIPIN PANDEY", "uniqueVehicleCount": 2},
        {"Transporter": "SHREE DEVI AGENCIES", "uniqueVehicleCount": 4},
        {"Transporter": "LOCALCASH", "uniqueVehicleCount": 149},
        {"Transporter": None, "uniqueVehicleCount": 482},
        {"Transporter": "M.R.TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "MAHAVIR TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "J PADMAVANI", "uniqueVehicleCount": 1},
        {"Transporter": "BHARATH transport", "uniqueVehicleCount": 1},
        {"Transporter": "CHANDRAKANT BHAGWAN MANE", "uniqueVehicleCount": 1},
        {"Transporter": "VINOD KUMAR YADAV", "uniqueVehicleCount": 3},
        {"Transporter": "BRAJENDRA PAL", "uniqueVehicleCount": 1},
        {"Transporter": "VRH LOGISTICS PVT LTD", "uniqueVehicleCount": 5},
        {"Transporter": "R. K. TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "JAI LAXMI TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "RAJKUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "SACHIN SANJAY DAUNDKAR", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE G.K. FREIGHT CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "ANJANA V AUGUSTINE", "uniqueVehicleCount": 1},
        {"Transporter": "NAFEES FATIMA MOHD. RAFIK SHAIKH", "uniqueVehicleCount": 1},
        {"Transporter": "CRM ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "DARA SREEKANTH", "uniqueVehicleCount": 1},
        {"Transporter": "GEETA DEVI", "uniqueVehicleCount": 1},
        {"Transporter": "MUZZAFFAR ALI", "uniqueVehicleCount": 2},
        {"Transporter": "SRI RANGA TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "B K LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SHIV SAI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "PRADIPTA KUMAR BARIK", "uniqueVehicleCount": 2},
        {"Transporter": "NITA S. NAIK", "uniqueVehicleCount": 2},
        {"Transporter": "NARESH MEHTO", "uniqueVehicleCount": 1},
        {"Transporter": "SAI ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "SHREE BALAJI TEMPO STAND UNION", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE GANESH ENTRPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "SANTOSH TIWARI", "uniqueVehicleCount": 2},
        {"Transporter": "HARSHJEET TRANSPORT SOLUTION", "uniqueVehicleCount": 1},
        {"Transporter": "JAGANATHAN M", "uniqueVehicleCount": 1},
        {"Transporter": "PRAVEEN.M.RAIKAR", "uniqueVehicleCount": 2},
        {"Transporter": "AAKASH AMARNATH CHOUDHARY", "uniqueVehicleCount": 8},
        {"Transporter": "ASHISH RANA", "uniqueVehicleCount": 2},
        {"Transporter": "SHIVAM TOURS AND TRAVELS", "uniqueVehicleCount": 9},
        {"Transporter": "SAJITH M S", "uniqueVehicleCount": 1},
        {"Transporter": "B.N. ROADWAYS", "uniqueVehicleCount": 7},
        {"Transporter": "RAHUL SHIRKE", "uniqueVehicleCount": 3},
        {"Transporter": "RAFIK SAB", "uniqueVehicleCount": 1},
        {"Transporter": "GOPAL MISHRA", "uniqueVehicleCount": 4},
        {"Transporter": "ASHISH LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "Saurabh Singh", "uniqueVehicleCount": 2},
        {"Transporter": "M SRINIVAS", "uniqueVehicleCount": 1},
        {"Transporter": "GIRISH NARAYAN AUTO TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "BRAMHANAND DATTARAM GADEKAR", "uniqueVehicleCount": 1},
        {"Transporter": "EJAZ AHMED", "uniqueVehicleCount": 1},
        {"Transporter": "SANTOSH KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "KAVYA ENTERPRISES", "uniqueVehicleCount": 5},
        {"Transporter": "VIJAY PRATAP SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "SANJAY TRAVELS", "uniqueVehicleCount": 3},
        {"Transporter": "SUN CITY EXPRESS", "uniqueVehicleCount": 1},
        {"Transporter": "M ARUMUGAM", "uniqueVehicleCount": 1},
        {"Transporter": "SURINDER KUMAR", "uniqueVehicleCount": 2},
        {"Transporter": "GANESH ASHOK CHAUDHARI", "uniqueVehicleCount": 1},
        {"Transporter": "G.SELVAM TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "SHAMSHAD", "uniqueVehicleCount": 2},
        {"Transporter": "NARASIMMAN M", "uniqueVehicleCount": 1},
        {"Transporter": "HITECH", "uniqueVehicleCount": 3},
        {"Transporter": "GOOD LUCK TOURS AND TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "VAIBHAV MAHENDRA BHOPI", "uniqueVehicleCount": 1},
        {"Transporter": "ANIL KUMAR", "uniqueVehicleCount": 3},
        {"Transporter": "SATISH KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "SKYPREVOIR UTILITY SERVICES PVT LTD", "uniqueVehicleCount": 1},
        {"Transporter": "INSTAMILE LOGISTICS PVT LTD", "uniqueVehicleCount": 1},
        {"Transporter": "RAVINDER SINGH", "uniqueVehicleCount": 4},
        {"Transporter": "RUDRA ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "B M  SUDHA RANI", "uniqueVehicleCount": 2},
        {"Transporter": "KARAMATH KHAN", "uniqueVehicleCount": 2},
        {"Transporter": "MOULA TAMBOLI", "uniqueVehicleCount": 1},
        {"Transporter": "JONI", "uniqueVehicleCount": 3},
        {"Transporter": "SATYA PRAVESH RANA", "uniqueVehicleCount": 3},
        {"Transporter": "MAHENDRA KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE HARMILAP TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "SANT SINGH", "uniqueVehicleCount": 4},
        {"Transporter": "SEBASTIAO ANTONIO WILSON LOURENCO", "uniqueVehicleCount": 1},
        {"Transporter": "GR TRANSPORT SOLUTION PVT LTD.", "uniqueVehicleCount": 2},
        {"Transporter": "JAY BHOLE TEMPO SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "TEKNOLOGIKOL LOGISTICS PRIVATE LIMI", "uniqueVehicleCount": 2},
        {"Transporter": "RAJESHWAR PRASAD", "uniqueVehicleCount": 1},
        {"Transporter": "BISMILLAH TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ATAUL BARI KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "DEEPAK KUMAR BARI", "uniqueVehicleCount": 1},
        {"Transporter": "PRINCE KUMAR SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "DINESH ROY", "uniqueVehicleCount": 1},
        {"Transporter": "BAJRANG RAI", "uniqueVehicleCount": 5},
        {"Transporter": "PUNIT KUMAR SHARMA", "uniqueVehicleCount": 2},
        {"Transporter": "M VENKATESH", "uniqueVehicleCount": 2},
        {"Transporter": "K S MURTHY", "uniqueVehicleCount": 3},
        {"Transporter": "SAYMA ROADLINES", "uniqueVehicleCount": 1},
        {"Transporter": "BIRENDER SINGH", "uniqueVehicleCount": 4},
        {"Transporter": "GEETA SOMASHEKAR NAIK", "uniqueVehicleCount": 2},
        {"Transporter": "YOGESH TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "SATYANARAYAN DARAK", "uniqueVehicleCount": 4},
        {"Transporter": "ANIL LADAK BARAD", "uniqueVehicleCount": 1},
        {"Transporter": "RAVINDRA DATTU SHENDARKAR", "uniqueVehicleCount": 2},
        {"Transporter": "Mahinder Kumar", "uniqueVehicleCount": 3},
        {"Transporter": "SHARATHKUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "ASSAM BOMBAY CARGO CARRIERS", "uniqueVehicleCount": 4},
        {"Transporter": "ON TIME TRANSOLUTIONS PVT LTD", "uniqueVehicleCount": 1},
        {"Transporter": "RAMSAN TRAVELS", "uniqueVehicleCount": 3},
        {"Transporter": "SRI AYYANNAR TRANSPORT", "uniqueVehicleCount": 4},
        {"Transporter": "SHAAGUN LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SHASHANK CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "MA KHAYYUM", "uniqueVehicleCount": 1},
        {"Transporter": "K GOVINDARAJU", "uniqueVehicleCount": 2},
        {"Transporter": "KAILAS RAVSAHEB PAWAL", "uniqueVehicleCount": 1},
        {"Transporter": "LASYA SREE LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "RAJU", "uniqueVehicleCount": 1},
        {"Transporter": "Balistar Shaw", "uniqueVehicleCount": 2},
        {"Transporter": "VIJENDRA N L", "uniqueVehicleCount": 1},
        {"Transporter": "INSTANT TRANSPORT SOLUTION (P) LTD", "uniqueVehicleCount": 21},
        {"Transporter": "JAY PRAKASH KUMAR", "uniqueVehicleCount": 2},
        {"Transporter": "MADHESWARAN P", "uniqueVehicleCount": 2},
        {"Transporter": "SAJIN P SUNNY", "uniqueVehicleCount": 1},
        {"Transporter": "RAHUL CARGO AND MOVERS SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "GOYAL TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": " SANTOSH KASHINATH SATHE", "uniqueVehicleCount": 1},
        {"Transporter": "KAMLESH KUMAR C YADAV", "uniqueVehicleCount": 1},
        {"Transporter": "LALCHAND R CHAUDHARY", "uniqueVehicleCount": 2},
        {"Transporter": "AARUSH TRANSWAYS", "uniqueVehicleCount": 1},
        {"Transporter": "SHOBHA EKNATH PILANE", "uniqueVehicleCount": 1},
        {"Transporter": "SHIVA SAKTHI LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "Satya Care solutions", "uniqueVehicleCount": 1},
        {"Transporter": "CCU CASH CONTRACTORS", "uniqueVehicleCount": 24},
        {"Transporter": "JAI LAXMI LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "Rajesh Dhokle", "uniqueVehicleCount": 1},
        {"Transporter": "MUNDHE TRANSPORT SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "RAHUL CARGO & MOVERS SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "PREM KUMAR SINGH", "uniqueVehicleCount": 5},
        {"Transporter": "SWAVAB.T.S", "uniqueVehicleCount": 1},
        {"Transporter": "P.KESAVAKUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "BHARAT A RATHOD", "uniqueVehicleCount": 1},
        {"Transporter": "PLatinium Trucking", "uniqueVehicleCount": 3},
        {"Transporter": "SHRIBRAHAMLALJI CARGO SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "VISHAL DALE", "uniqueVehicleCount": 4},
        {"Transporter": "SHIV MOHAN THAKUR", "uniqueVehicleCount": 1},
        {"Transporter": "TAHASHILDAR RAJBHAR", "uniqueVehicleCount": 1},
        {"Transporter": "RAVISHANKAR MISHRA", "uniqueVehicleCount": 1},
        {"Transporter": "SURESH LAXMAN MORE", "uniqueVehicleCount": 4},
        {"Transporter": "Paul Enterprise", "uniqueVehicleCount": 10},
        {"Transporter": "NANGHA MAYUR KISHORBHAI", "uniqueVehicleCount": 1},
        {"Transporter": "HARISH CHANDRA KUSALKAR", "uniqueVehicleCount": 1},
        {"Transporter": "MANTU KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "ALLRAKHA A SANGHARIYAT", "uniqueVehicleCount": 1},
        {"Transporter": "NAGRAJ K N", "uniqueVehicleCount": 1},
        {"Transporter": "SUN CITY EXPRESS SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "RAGHUBIR", "uniqueVehicleCount": 1},
        {"Transporter": "RAJ GOPAL A", "uniqueVehicleCount": 1},
        {"Transporter": "KHALA L", "uniqueVehicleCount": 1},
        {"Transporter": "PRABHU N", "uniqueVehicleCount": 1},
        {"Transporter": "CHANDRAKANT BHAVE", "uniqueVehicleCount": 1},
        {"Transporter": "A.PALANIVEL", "uniqueVehicleCount": 1},
        {"Transporter": "K VAIRAMUTHU", "uniqueVehicleCount": 2},
        {"Transporter": "SRI MEENAKSHAMMA TEMPO SERIVCE", "uniqueVehicleCount": 1},
        {"Transporter": "VANSH LOGISTICS", "uniqueVehicleCount": 8},
        {"Transporter": "KRISHNA TRANSPORT SERVICES", "uniqueVehicleCount": 5},
        {"Transporter": "CHHAYA PRAKASH BAGADI", "uniqueVehicleCount": 2},
        {"Transporter": "BBT Transport", "uniqueVehicleCount": 1},
        {"Transporter": "DELHI VAPI ROADLINES", "uniqueVehicleCount": 6},
        {"Transporter": "SAMPATHE CARRIERS", "uniqueVehicleCount": 2},
        {"Transporter": "LALJI PAL", "uniqueVehicleCount": 1},
        {"Transporter": "G.KAVYA TRANSPORT", "uniqueVehicleCount": 7},
        {"Transporter": "SHANTI TRANSPORT COMPANY", "uniqueVehicleCount": 5},
        {"Transporter": "ANIL KUMAR N", "uniqueVehicleCount": 1},
        {"Transporter": "MANJOT ROADLINES", "uniqueVehicleCount": 1},
        {"Transporter": "RAO TRANSPORT CO", "uniqueVehicleCount": 1},
        {"Transporter": "GULSHAN S BARAPATRE", "uniqueVehicleCount": 1},
        {"Transporter": "SUNIL TEMPO SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "GAURAV THAKUR", "uniqueVehicleCount": 1},
        {"Transporter": "YASODHADEVI N", "uniqueVehicleCount": 1},
        {"Transporter": "Gurpreet Kaur", "uniqueVehicleCount": 1},
        {"Transporter": "D.K.LOGISTICS", "uniqueVehicleCount": 10},
        {"Transporter": "SAKSHAM TRADERS", "uniqueVehicleCount": 1},
        {"Transporter": "SAGAR TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "R VENKATA NARAYANA RAO", "uniqueVehicleCount": 1},
        {"Transporter": "NG TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "PERFECT MOTOR GARRAGE", "uniqueVehicleCount": 1},
        {"Transporter": "SAMARTH ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "MAANASVI CARGO LOGESTICS", "uniqueVehicleCount": 7},
        {"Transporter": "NAGARAM JAGAN MOHAN RAO", "uniqueVehicleCount": 1},
        {"Transporter": "SACHIN H C", "uniqueVehicleCount": 2},
        {"Transporter": "VALLABHASETTI NAGASHESU", "uniqueVehicleCount": 1},
        {"Transporter": "NILESH", "uniqueVehicleCount": 1},
        {"Transporter": "VAIBHAV KRUSHNARAO THETE", "uniqueVehicleCount": 1},
        {"Transporter": "DEEPAK JANARDHAN SHIRKE", "uniqueVehicleCount": 1},
        {"Transporter": "HEMANT LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "LEO ENTERPRISES", "uniqueVehicleCount": 3},
        {"Transporter": "Amar Singh Chawhan", "uniqueVehicleCount": 1},
        {"Transporter": "SHARAVAN NATH LADU NATH RAWAL", "uniqueVehicleCount": 1},
        {"Transporter": "K.P. ASWIN", "uniqueVehicleCount": 1},
        {"Transporter": "JAI DEEP SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "K RADHIKA", "uniqueVehicleCount": 1},
        {"Transporter": "DINESH TEMPO", "uniqueVehicleCount": 7},
        {"Transporter": "C. PADMAVATHI", "uniqueVehicleCount": 1},
        {"Transporter": "AARTI YADAV", "uniqueVehicleCount": 1},
        {"Transporter": "MAYURESHWAR LOGISTICS PRIVATE LIMITT", "uniqueVehicleCount": 10},
        {"Transporter": "ASIAN CAR RENTAL", "uniqueVehicleCount": 3},
        {"Transporter": "SAI STUTI TEMPO SERVICE", "uniqueVehicleCount": 4},
        {"Transporter": "VISHNU T K", "uniqueVehicleCount": 1},
        {"Transporter": "PRADEEP KUMAR ROUT", "uniqueVehicleCount": 1},
        {"Transporter": "SUNDER LAL", "uniqueVehicleCount": 1},
        {"Transporter": "EKVEERA AAI ENTERPRISES", "uniqueVehicleCount": 3},
        {"Transporter": "AJAY TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ANUP", "uniqueVehicleCount": 1},
        {"Transporter": "INDRASHAN P PAL", "uniqueVehicleCount": 1},
        {"Transporter": "RAGHUNATH REDDY", "uniqueVehicleCount": 4},
        {"Transporter": "ASHUTOSH ROADLINES", "uniqueVehicleCount": 2},
        {"Transporter": "S.M.V ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "DINESH PRASAD SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "NAGENDRA", "uniqueVehicleCount": 1},
        {"Transporter": "PRABHAT CARGO MOVERS", "uniqueVehicleCount": 1},
        {"Transporter": "ANNA ASHOK GALANDE", "uniqueVehicleCount": 1},
        {"Transporter": "KRISHNA TRAVELS", "uniqueVehicleCount": 6},
        {"Transporter": "RAHUL TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "RUDVIKA LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "AJIT SINGH", "uniqueVehicleCount": 3},
        {"Transporter": "ARUNKUMAR RAMAKEBAL SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "YADAV TRANSPORT", "uniqueVehicleCount": 14},
        {"Transporter": "JAYA NIVEDHA", "uniqueVehicleCount": 1},
        {"Transporter": "NATHA SINGH", "uniqueVehicleCount": 4},
        {"Transporter": "PRABHAKAR RAMA PATIL", "uniqueVehicleCount": 1},
        {"Transporter": "IS ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "THARIKA SRI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "NARINDRA KUMAR", "uniqueVehicleCount": 2},
        {"Transporter": "KMG Logistics", "uniqueVehicleCount": 2},
        {"Transporter": "POWER EXPRESS LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "NARAYAN CHANDRA DEY", "uniqueVehicleCount": 1},
        {"Transporter": "MPS TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ROBERT KUMAR", "uniqueVehicleCount": 2},
        {"Transporter": "AMAR CHAND AND SONS", "uniqueVehicleCount": 6},
        {"Transporter": "NARENDRA TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "AKASH CHAUDHARY", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE TPT", "uniqueVehicleCount": 1},
        {"Transporter": "NAGARAJ K. N", "uniqueVehicleCount": 1},
        {"Transporter": "All to let Services", "uniqueVehicleCount": 1},
        {"Transporter": "S.MANIKANDAN", "uniqueVehicleCount": 1},
        {"Transporter": "N S TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "TULE TRANSPORTS", "uniqueVehicleCount": 2},
        {"Transporter": "SAFETRANS SYSTEMS", "uniqueVehicleCount": 1},
        {"Transporter": "KALPESH ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "R.MALLIKA", "uniqueVehicleCount": 1},
        {"Transporter": "K.L.THOMAS", "uniqueVehicleCount": 1},
        {"Transporter": "R. P. LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "RAJESH SHIRKE", "uniqueVehicleCount": 3},
        {"Transporter": "YUVARAJ TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "ARIF", "uniqueVehicleCount": 1},
        {"Transporter": "SPARSH TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "YADAV ROAD CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "MIDHA FRIEGHT CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "NITIN ASHOK LOKHANDE", "uniqueVehicleCount": 1},
        {"Transporter": "RANJEET TOUR & TRAVELS", "uniqueVehicleCount": 2},
        {"Transporter": "KUNJACHAN K J", "uniqueVehicleCount": 1},
        {"Transporter": "MAHADEVA", "uniqueVehicleCount": 1},
        {"Transporter": "A S TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "EUB CASH CONTRACTOR", "uniqueVehicleCount": 5},
        {"Transporter": "INDRAKUMAR B SHARMA", "uniqueVehicleCount": 2},
        {"Transporter": "DINESH TEMPO SERVICE", "uniqueVehicleCount": 29},
        {"Transporter": "OC TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "NAWAZ", "uniqueVehicleCount": 1},
        {"Transporter": "RAMESH SATPUTE", "uniqueVehicleCount": 1},
        {"Transporter": "SHIVRAJ ENTERPRISE", "uniqueVehicleCount": 1},
        {"Transporter": "R.P.LOGISTICS", "uniqueVehicleCount": 4},
        {"Transporter": "TROLLTECH ENGINEERING WORKS REG.", "uniqueVehicleCount": 4},
        {"Transporter": "VALLABHASETTI  NAGASESHU", "uniqueVehicleCount": 1},
        {"Transporter": "PARAMESHA B L", "uniqueVehicleCount": 1},
        {"Transporter": "RAJ ROADLINES", "uniqueVehicleCount": 1},
        {"Transporter": "SRL TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ZENITH LOGISTICS AND EXPRESS SERVICES PVT LTD", "uniqueVehicleCount": 6},
        {"Transporter": "K.SURENDREN", "uniqueVehicleCount": 1},
        {"Transporter": "VAIRAMUTHU P", "uniqueVehicleCount": 1},
        {"Transporter": "DARSHAN TAXI SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "KUNAL TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "HINDAVI TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "MOHD SALLAUDDIN SAHA", "uniqueVehicleCount": 2},
        {"Transporter": "NIRANJAN KUMAR SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "NEERAJ KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "ASPAK", "uniqueVehicleCount": 3},
        {"Transporter": "RAJESH", "uniqueVehicleCount": 1},
        {"Transporter": "SHRI RAM CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "AMOL M. CHOUDHARI", "uniqueVehicleCount": 1},
        {"Transporter": "DHANA LAKSHMI SAIKAM", "uniqueVehicleCount": 1},
        {"Transporter": "SANTOSH KUMAR SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "BIRENDRA KUMAR SHUKLA", "uniqueVehicleCount": 1},
        {"Transporter": "S SHASHIDHAR", "uniqueVehicleCount": 1},
        {"Transporter": "VIJAY POOJARY", "uniqueVehicleCount": 2},
        {"Transporter": "SUNIL R. SHARMA", "uniqueVehicleCount": 4},
        {"Transporter": "KATAMONI NAGENDRAM GOUD", "uniqueVehicleCount": 3},
        {"Transporter": "RAMESH TRAVEL COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "RAHUL TRAVELS AND CARGO", "uniqueVehicleCount": 1},
        {"Transporter": "KISHAN SHARMA", "uniqueVehicleCount": 3},
        {"Transporter": "DEVENDRAN M", "uniqueVehicleCount": 2},
        {"Transporter": "Ghosh Enterprise", "uniqueVehicleCount": 1},
        {"Transporter": "JAGDISH TEMPO SERVICE", "uniqueVehicleCount": 4},
        {"Transporter": "SHIV CARGO", "uniqueVehicleCount": 1},
        {"Transporter": "GM TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "MY LOGISTIC", "uniqueVehicleCount": 1},
        {"Transporter": "SRI GOKULRAJ TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SHIV SHANKAR TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "SABBIRBHAI V SANGHARIYAT", "uniqueVehicleCount": 2},
        {"Transporter": "ANAND BHUSHAN", "uniqueVehicleCount": 1},
        {"Transporter": "A THAMIM YASIN", "uniqueVehicleCount": 1},
        {"Transporter": "RIZWANA SULTHANA", "uniqueVehicleCount": 1},
        {"Transporter": "STAR INDIA HR SOLUTIONS PVT LTD    ", "uniqueVehicleCount": 1},
        {"Transporter": "UDHAV KESHAVRAO DUKRE", "uniqueVehicleCount": 1},
        {"Transporter": "NITIN DATTU SARWADE", "uniqueVehicleCount": 2},
        {"Transporter": "NIKHIL SHIVAJI CHAVAN", "uniqueVehicleCount": 1},
        {"Transporter": "MAHINDER MISHRA", "uniqueVehicleCount": 1},
        {"Transporter": "CAMIONS LOGISTICS SOLUTIONS PVT LTD", "uniqueVehicleCount": 1},
        {"Transporter": "YOGESH SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "RAVIKUMAR S", "uniqueVehicleCount": 1},
        {"Transporter": "MANDEEP TEMPO", "uniqueVehicleCount": 1},
        {"Transporter": "SAMARTH ROADLINES", "uniqueVehicleCount": 15},
        {"Transporter": "R ARUNACHALAM", "uniqueVehicleCount": 1},
        {"Transporter": "ASHOK KUMARI", "uniqueVehicleCount": 1},
        {"Transporter": "MOHANLAL LALAN SONAR", "uniqueVehicleCount": 1},
        {"Transporter": "MOHD.A.KHADAR", "uniqueVehicleCount": 2},
        {"Transporter": "JOSHAN TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "JITENDRA KOUL", "uniqueVehicleCount": 1},
        {"Transporter": "ANJANA AUGUSTIN", "uniqueVehicleCount": 1},
        {"Transporter": "HARISH", "uniqueVehicleCount": 1},
        {"Transporter": "MARIMUTHU", "uniqueVehicleCount": 1},
        {"Transporter": "DARSHAN SINGH", "uniqueVehicleCount": 2},
        {"Transporter": "RAHIL CARGO", "uniqueVehicleCount": 2},
        {"Transporter": "SEVENHILLS ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "KULDEEP KUMAR", "uniqueVehicleCount": 4},
        {"Transporter": "BHARDWAJ TRAVELS", "uniqueVehicleCount": 8},
        {"Transporter": "ASHIA TRANSPORT CO.", "uniqueVehicleCount": 1},
        {"Transporter": "SHIV PAHAL LOGISTICS SOLUTION", "uniqueVehicleCount": 1},
        {"Transporter": "INBOUND XPRESS LOGISTICS SOLUTIONS ", "uniqueVehicleCount": 1},
        {"Transporter": "YASMINE RAFATH", "uniqueVehicleCount": 9},
        {"Transporter": "RUPA ROY CHOWDHURY", "uniqueVehicleCount": 1},
        {"Transporter": "SHEKHAVATI CARGO CARRIERS", "uniqueVehicleCount": 2},
        {"Transporter": "MAHI TRANSPORT AND TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "ABHAY ROADLINES", "uniqueVehicleCount": 1},
        {"Transporter": "Vishnu K A", "uniqueVehicleCount": 1},
        {"Transporter": "JUST IN TIME SERVICES", "uniqueVehicleCount": 6},
        {"Transporter": "GURUPRASAD N S", "uniqueVehicleCount": 2},
        {"Transporter": "BWH CASH CONTRACTORS", "uniqueVehicleCount": 74},
        {"Transporter": "KRISHNA", "uniqueVehicleCount": 1},
        {"Transporter": "MULLA AZARODEEN LAYAKALI", "uniqueVehicleCount": 1},
        {"Transporter": "V R AGENCIES", "uniqueVehicleCount": 2},
        {"Transporter": "SHREE SHIV CARGO CARRIER", "uniqueVehicleCount": 2},
        {"Transporter": "MAHARASHTRAS TRANSPORT SERIVSES", "uniqueVehicleCount": 1},
        {"Transporter": "S.MANIGANDAN", "uniqueVehicleCount": 1},
        {"Transporter": "Vasila Roadways", "uniqueVehicleCount": 3},
        {"Transporter": "JITENDER DUBEY", "uniqueVehicleCount": 1},
        {"Transporter": "BD & COMPANY", "uniqueVehicleCount": 2},
        {"Transporter": "ANKILLA NAGAMANI", "uniqueVehicleCount": 1},
        {"Transporter": "R P LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "CLOCKWORK MULTIFREIGHT SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "SACHIN MANE TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SAFEWAY LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SANTHI NARAYAN ROAD TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SRI KRISHNA ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "THIRUMURUGAN TRANSPORT", "uniqueVehicleCount": 8},
        {"Transporter": "GAJENDRA BALU GHOTKULE", "uniqueVehicleCount": 2},
        {"Transporter": "AISHWARRY TRANS", "uniqueVehicleCount": 1},
        {"Transporter": "SHANMUGAN", "uniqueVehicleCount": 1},
        {"Transporter": "ROYAL TRANSPORT SOLUTIONS", "uniqueVehicleCount": 4},
        {"Transporter": "YADAV TEMPO SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "SHESH NARAYAN GHOTKULE", "uniqueVehicleCount": 2},
        {"Transporter": "MADAN BABAN CHANDORE", "uniqueVehicleCount": 1},
        {"Transporter": "ANIL PANDURANG AMALE", "uniqueVehicleCount": 1},
        {"Transporter": "V.NARASIMHAN", "uniqueVehicleCount": 1},
        {"Transporter": "SAMRAT LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "CSD TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "S L V ENTERPRISES", "uniqueVehicleCount": 3},
        {"Transporter": "JOTHIMOORTHY", "uniqueVehicleCount": 2},
        {"Transporter": "RD LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "SHAIK ATEEQUR RAHAMAN", "uniqueVehicleCount": 1},
        {"Transporter": "HANDCARRY", "uniqueVehicleCount": 1},
        {"Transporter": "MANIKANTA K N", "uniqueVehicleCount": 1},
        {"Transporter": "SIARA TRANS", "uniqueVehicleCount": 2},
        {"Transporter": "SHARAD MHASKE", "uniqueVehicleCount": 1},
        {"Transporter": "DINESH CHATURVEDI", "uniqueVehicleCount": 3},
        {"Transporter": "KAMESHWARAN B", "uniqueVehicleCount": 1},
        {"Transporter": "ADITI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": " D KANAGARAJ", "uniqueVehicleCount": 1},
        {"Transporter": "SRIMAAN LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "S WILSON LOURENCO-GA01-Z1007", "uniqueVehicleCount": 2},
        {"Transporter": "GANGARAMOENA PUSHPA", "uniqueVehicleCount": 1},
        {"Transporter": "VISHAL DALE AUTO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "D ROY ENTERPRISE", "uniqueVehicleCount": 17},
        {"Transporter": "AJAYA KUMAR BEHERA", "uniqueVehicleCount": 2},
        {"Transporter": "SMITA ROADWAYS", "uniqueVehicleCount": 2},
        {"Transporter": "SAI YATRA CARGO", "uniqueVehicleCount": 3},
        {"Transporter": "AAKASH LOGISTIC", "uniqueVehicleCount": 2},
        {"Transporter": "MEGHRAJ TURKAR", "uniqueVehicleCount": 1},
        {"Transporter": "ECS WORLD WIDE EXPRESS", "uniqueVehicleCount": 1},
        {"Transporter": "SUBHASH CHAND", "uniqueVehicleCount": 10},
        {"Transporter": "GIRIJA SHANKAR TIWARI", "uniqueVehicleCount": 2},
        {"Transporter": "SINGH ENTERPRISE", "uniqueVehicleCount": 3},
        {"Transporter": "MANISH LOGISTICS (INDIA)", "uniqueVehicleCount": 2},
        {"Transporter": "KIRAN SHRIHARI MADAVI", "uniqueVehicleCount": 3},
        {"Transporter": "MANISHBHAI BHATT", "uniqueVehicleCount": 1},
        {"Transporter": "R.NANDHAKUMARI", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE MAULI PRASAD ROAD LINES", "uniqueVehicleCount": 1},
        {"Transporter": "AARTI CARGO MOVERS", "uniqueVehicleCount": 1},
        {"Transporter": "SANJAY NATHU BALKAWADE", "uniqueVehicleCount": 1},
        {"Transporter": "VENKATESH BABU S R", "uniqueVehicleCount": 2},
        {"Transporter": "MUB CASH CONTRACTORS", "uniqueVehicleCount": 15},
        {"Transporter": "BOLEM SURIBABU", "uniqueVehicleCount": 1},
        {"Transporter": "G D PANSARE", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE KRISHNA ROAD CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "S L LOGISTICS & INFRA", "uniqueVehicleCount": 1},
        {"Transporter": "K.KARTHIKA", "uniqueVehicleCount": 1},
        {"Transporter": "SHALU", "uniqueVehicleCount": 2},
        {"Transporter": "ANTONY SHANNON ROZARIO", "uniqueVehicleCount": 1},
        {"Transporter": "TEJAS DIGAMBAR KEDARI", "uniqueVehicleCount": 1},
        {"Transporter": "SAJ TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "MOHANDAS B", "uniqueVehicleCount": 2},
        {"Transporter": "ARYAN LOGISTICS", "uniqueVehicleCount": 6},
        {"Transporter": "BSA LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "GOODLUCK TOURS AND TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "HWH CASH CONTRACTOR", "uniqueVehicleCount": 5},
        {"Transporter": "SALAHUDIN GOODS CARRIER", "uniqueVehicleCount": 4},
        {"Transporter": "SHRI KUMAR ROADLINES", "uniqueVehicleCount": 3},
        {"Transporter": "GORAKH NIVRUTTI LOKHANDE", "uniqueVehicleCount": 1},
        {"Transporter": "BALESHWAR YADAV", "uniqueVehicleCount": 2},
        {"Transporter": "BHARWAD RAGHUBHAI GAGJIBHAI", "uniqueVehicleCount": 1},
        {"Transporter": "PAWAN PUTAR TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "ANITHA", "uniqueVehicleCount": 6},
        {"Transporter": "NARENDER", "uniqueVehicleCount": 1},
        {"Transporter": "AMAR ANANDFA DAS", "uniqueVehicleCount": 8},
        {"Transporter": "RIZWAN ULLA KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "P K CARGO MOVERS", "uniqueVehicleCount": 3},
        {"Transporter": "SAQUIBR.ZAIDI", "uniqueVehicleCount": 1},
        {"Transporter": "NAMAN ROADLINES", "uniqueVehicleCount": 3},
        {"Transporter": "SUNDARAPPA C", "uniqueVehicleCount": 2},
        {"Transporter": "K.VAIRAMUTHU", "uniqueVehicleCount": 2},
        {"Transporter": "SANTOSH KACHARU TEMGHARE", "uniqueVehicleCount": 1},
        {"Transporter": "BITTU FAX STD & PCO", "uniqueVehicleCount": 1},
        {"Transporter": "C M CHANDRASHEKAR", "uniqueVehicleCount": 2},
        {"Transporter": "ANAND MOHAN", "uniqueVehicleCount": 5},
        {"Transporter": "CHETAK TRANSPORT CO", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE BALAJI LOGISTIC", "uniqueVehicleCount": 1},
        {"Transporter": "M.DHANUSU", "uniqueVehicleCount": 1},
        {"Transporter": "JETEX PARCEL SYSTEMS PVT. LTD.", "uniqueVehicleCount": 3},
        {"Transporter": "KUPPUSWAMY", "uniqueVehicleCount": 1},
        {"Transporter": "Sheetal Kumar Verma", "uniqueVehicleCount": 1},
        {"Transporter": "AMIT MEHTA", "uniqueVehicleCount": 1},
        {"Transporter": "VIHANG TRANS SOLUTIONS", "uniqueVehicleCount": 1},
        {"Transporter": "BHISE TRANSPORT SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "R.D LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "DISHA LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SMITA RATNAKANT KERKAR", "uniqueVehicleCount": 1},
        {"Transporter": "MANOJ KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "ARIVAZHAGAN.S", "uniqueVehicleCount": 1},
        {"Transporter": "SHAHID ROADLINES", "uniqueVehicleCount": 1},
        {"Transporter": "K T ENTERPRISES", "uniqueVehicleCount": 4},
        {"Transporter": "MISHRA TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "RAJAGOPAL ALLI", "uniqueVehicleCount": 1},
        {"Transporter": "DHEERAJ SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "SANJIT SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "MADHU M G", "uniqueVehicleCount": 1},
        {"Transporter": "GEETA SANWAL", "uniqueVehicleCount": 1},
        {"Transporter": "SANJAY SAKHARAM JADHAV", "uniqueVehicleCount": 3},
        {"Transporter": "S.SRIDHAR", "uniqueVehicleCount": 2},
        {"Transporter": "ASEEF HUSSAIN N", "uniqueVehicleCount": 1},
        {"Transporter": "JAY SHANKAR CARGO", "uniqueVehicleCount": 1},
        {"Transporter": "VARAHI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SUKUMARY P K", "uniqueVehicleCount": 1},
        {"Transporter": "AMIR SALAUDIN SHAIKH", "uniqueVehicleCount": 1},
        {"Transporter": "VIJAYA ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "SEEMA GAJENDRA NILE", "uniqueVehicleCount": 2},
        {"Transporter": "DATTATAREY BAJARANG MORE", "uniqueVehicleCount": 1},
        {"Transporter": "APARNA TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "SAMARPAN TRANSPORT AND MANPOWER SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "SANDIP MARUTI DEVKAR", "uniqueVehicleCount": 2},
        {"Transporter": "BEGUMPUR KHATOLA TRANSPORT UNION", "uniqueVehicleCount": 1},
        {"Transporter": "SPEEDWAY EXPRESS", "uniqueVehicleCount": 1},
        {"Transporter": "JAI SHREE BALAJI LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "RADHESHYAMAGARWAL", "uniqueVehicleCount": 1},
        {"Transporter": "SUBHASHBHAI R JAT", "uniqueVehicleCount": 1},
        {"Transporter": "ANANDA KUMAR N", "uniqueVehicleCount": 2},
        {"Transporter": "JALINDAR SHIVAJI KAITKE", "uniqueVehicleCount": 2},
        {"Transporter": "K V TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "JAI HANUMAN LOGOISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "S.VIMALRAJ", "uniqueVehicleCount": 6},
        {"Transporter": "PRITESH GANESH BHOIR", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE TRANSPORT SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "AMAR CHAND & SONS (HUF)", "uniqueVehicleCount": 4},
        {"Transporter": "MANOJ KUMAR MISHRA", "uniqueVehicleCount": 1},
        {"Transporter": "CHOUDHURY BROTHERS", "uniqueVehicleCount": 1},
        {"Transporter": "K.V. TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "DIDAR SINGH", "uniqueVehicleCount": 3},
        {"Transporter": "MANE TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SHRAVAN L. RAVAL", "uniqueVehicleCount": 1},
        {"Transporter": "NARENDRA L PATEL", "uniqueVehicleCount": 2},
        {"Transporter": "URMILA RAJMANI MISHRA", "uniqueVehicleCount": 1},
        {"Transporter": "HIMANSHU EXPRESS CARGO MOVERS", "uniqueVehicleCount": 1},
        {"Transporter": "BARIGALA VEERASWAMI", "uniqueVehicleCount": 2},
        {"Transporter": "NEW CITY CARRIER", "uniqueVehicleCount": 15},
        {"Transporter": "COURIER LOGISTIC", "uniqueVehicleCount": 1},
        {"Transporter": "MUFFADAL M MODI", "uniqueVehicleCount": 2},
        {"Transporter": "BAJWA ROADLINES (INDIA)", "uniqueVehicleCount": 4},
        {"Transporter": "K RAJENDIRAN", "uniqueVehicleCount": 1},
        {"Transporter": "DUBEY TRANSPORTATION", "uniqueVehicleCount": 4},
        {"Transporter": "SANJAY CHARI", "uniqueVehicleCount": 1},
        {"Transporter": "SIRAJ AHMED KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "DIPALI AVINASH AWHALE", "uniqueVehicleCount": 2},
        {"Transporter": "V.ANITHA", "uniqueVehicleCount": 3},
        {"Transporter": "DEEPAK CHAND VISHWAKARMA", "uniqueVehicleCount": 2},
        {"Transporter": "AHMED BASHA", "uniqueVehicleCount": 1},
        {"Transporter": "KAPOOR DIESELS GARAGE PVT.LTD.", "uniqueVehicleCount": 14},
        {"Transporter": "R LAKSHMI TEJASWI", "uniqueVehicleCount": 1},
        {"Transporter": "PRABHAVATHI", "uniqueVehicleCount": 1},
        {"Transporter": "D.SRINIVASAN -SRM", "uniqueVehicleCount": 1},
        {"Transporter": "MAYURESHWAR LOGISTICS PRIVATE LIMITED", "uniqueVehicleCount": 1},
        {"Transporter": "KUSH LOGISTIC SERVICES", "uniqueVehicleCount": 3},
        {"Transporter": "SHASHIKUMAR SABHASHANKAR DUBEY", "uniqueVehicleCount": 2},
        {"Transporter": "T & F EXPRESS", "uniqueVehicleCount": 9},
        {"Transporter": "SHRIKUL TRACTORS", "uniqueVehicleCount": 1},
        {"Transporter": "Armaan Enterprises", "uniqueVehicleCount": 1},
        {"Transporter": "GIRRAJ TRANSPORT", "uniqueVehicleCount": 4},
        {"Transporter": "JIVANBHAI GAGJIBHAI BHARWAD", "uniqueVehicleCount": 2},
        {"Transporter": "SREEBASH.M", "uniqueVehicleCount": 1},
        {"Transporter": "SHARMAANILKUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "MANJUNATH S", "uniqueVehicleCount": 1},
        {"Transporter": "C.SURESH", "uniqueVehicleCount": 1},
        {"Transporter": "C SINGARAVELU", "uniqueVehicleCount": 1},
        {"Transporter": "DYAL SINGH", "uniqueVehicleCount": 2},
        {"Transporter": "M.RAJALAKSHMI", "uniqueVehicleCount": 2},
        {"Transporter": "SHRAWANI ROADLINE", "uniqueVehicleCount": 3},
        {"Transporter": "CHANDER SHEKHAR TRANSPORT CO", "uniqueVehicleCount": 1},
        {"Transporter": "NAV LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "BABURAM BHAYYARAM AGARWAL", "uniqueVehicleCount": 5},
        {"Transporter": "D K LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "ANURADHA CHOUDHARI", "uniqueVehicleCount": 1},
        {"Transporter": "HARSHIT GOWDA N", "uniqueVehicleCount": 2},
        {"Transporter": "R V NARAYANA RAO", "uniqueVehicleCount": 2},
        {"Transporter": "DEVAMANI LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "DILSHAD ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "ROHIT GABALE", "uniqueVehicleCount": 1},
        {"Transporter": "HG PRIME LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "JINEESH VALIYAPARAMBIL", "uniqueVehicleCount": 1},
        {"Transporter": "SHIV KOHLI", "uniqueVehicleCount": 1},
        {"Transporter": "POLIPATHI NITHIN", "uniqueVehicleCount": 1},
        {"Transporter": "MOHAMMAD ABBAS", "uniqueVehicleCount": 1},
        {"Transporter": "SUSHIL TEMPO SERVICE", "uniqueVehicleCount": 5},
        {"Transporter": "NANDAN SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "HAUSHIRAM DAGDU GAWADE", "uniqueVehicleCount": 1},
        {"Transporter": "DIPTAB VENTURES PRIVATE LIMITED", "uniqueVehicleCount": 6},
        {"Transporter": "G KRISHNA", "uniqueVehicleCount": 1},
        {"Transporter": "SA LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "BHISE TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "BIJENDER PAL TRANSPORT CO.", "uniqueVehicleCount": 6},
        {"Transporter": "ROYAL ENTERPRISE", "uniqueVehicleCount": 10},
        {"Transporter": "ROHIDAS GAUDE", "uniqueVehicleCount": 1},
        {"Transporter": "CHARANJIT SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "GARGI TOURS & TRAVELS", "uniqueVehicleCount": 7},
        {"Transporter": "KRISHNA TRANSPORT SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "SATYAVAN HOUSHIRAM GAWADE", "uniqueVehicleCount": 3},
        {"Transporter": "MULLA SHABODHIN", "uniqueVehicleCount": 1},
        {"Transporter": "MAYUR FRIGHT CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "ATC E-HORIZON", "uniqueVehicleCount": 8},
        {"Transporter": "JATINDER SINGH AND CO.", "uniqueVehicleCount": 1},
        {"Transporter": "SUBRAMANYA", "uniqueVehicleCount": 1},
        {"Transporter": "BAKKI RAJU", "uniqueVehicleCount": 1},
        {"Transporter": "KHUMAN EXPRESS ", "uniqueVehicleCount": 3},
        {"Transporter": "R S TRANSPORT SERVICES", "uniqueVehicleCount": 2},
        {"Transporter": "S.PALANI", "uniqueVehicleCount": 1},
        {"Transporter": "RAGHU NATH SAHNI", "uniqueVehicleCount": 1},
        {"Transporter": "K SURENDRAN", "uniqueVehicleCount": 2},
        {"Transporter": "NISSAN COURIERS", "uniqueVehicleCount": 2},
        {"Transporter": "S.GANDHIMATHI", "uniqueVehicleCount": 2},
        {"Transporter": "RAMJI TIWARI", "uniqueVehicleCount": 3},
        {"Transporter": "K-EXPRESS", "uniqueVehicleCount": 1},
        {"Transporter": "UJJWAL SAINATH KAMBLE", "uniqueVehicleCount": 1},
        {"Transporter": "R.KANI", "uniqueVehicleCount": 1},
        {"Transporter": "SHIVAM TOUR AND TRAVEL", "uniqueVehicleCount": 1},
        {"Transporter": "SUDHAKAR NAMDEV KOLEKAR", "uniqueVehicleCount": 2},
        {"Transporter": "M.R.V.TRANSPORT", "uniqueVehicleCount": 4},
        {"Transporter": "BHARAT A. RATHOD", "uniqueVehicleCount": 1},
        {"Transporter": "SHARAD ANNA AUTADE", "uniqueVehicleCount": 1},
        {"Transporter": "MURLIDHAR ROAD LINES", "uniqueVehicleCount": 1},
        {"Transporter": "SHRAVAN LADU RAVAL", "uniqueVehicleCount": 1},
        {"Transporter": "GIRIDAS NARAYAN PATIL", "uniqueVehicleCount": 1},
        {"Transporter": "BHUI GOODS CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "AMOL GARAD", "uniqueVehicleCount": 1},
        {"Transporter": "OM PRAKASH LOHIA", "uniqueVehicleCount": 1},
        {"Transporter": "VIKAS SINGH", "uniqueVehicleCount": 3},
        {"Transporter": "RAMESH TRAVELS", "uniqueVehicleCount": 2},
        {"Transporter": "Phoolchandra Yadav", "uniqueVehicleCount": 1},
        {"Transporter": "GULLU BUDHIRAM YADAV", "uniqueVehicleCount": 1},
        {"Transporter": "KSP TRANSPORT & LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "ANIL KUMAR B S", "uniqueVehicleCount": 1},
        {"Transporter": "YADAV TRANSPORT SERVICE", "uniqueVehicleCount": 12},
        {"Transporter": "GR TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "NANDU PARSHURAM MANDAVKAR", "uniqueVehicleCount": 1},
        {"Transporter": "ARUMUGAM.S", "uniqueVehicleCount": 1},
        {"Transporter": "K VENKATESWARA RAO", "uniqueVehicleCount": 1},
        {"Transporter": "SUMESH SUKUMARAN", "uniqueVehicleCount": 1},
        {"Transporter": "SHIVAM TOUR & TRAVELS", "uniqueVehicleCount": 3},
        {"Transporter": "SHIVAJI HUCHAPPA KURANE", "uniqueVehicleCount": 1},
        {"Transporter": "VIKAS BAGRI", "uniqueVehicleCount": 2},
        {"Transporter": "RAJ KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "P MURUGAN", "uniqueVehicleCount": 1},
        {"Transporter": "World Solution", "uniqueVehicleCount": 1},
        {"Transporter": "S RAGHUNATH REDDY", "uniqueVehicleCount": 4},
        {"Transporter": "BASAVARAJ.K.JAMBAGI", "uniqueVehicleCount": 2},
        {"Transporter": "B.RAMESH BABU", "uniqueVehicleCount": 1},
        {"Transporter": "NARESH KHATIK", "uniqueVehicleCount": 1},
        {"Transporter": "UNITED TRANSPORT CORPORATION", "uniqueVehicleCount": 1},
        {"Transporter": "ASHOK PATIL", "uniqueVehicleCount": 2},
        {"Transporter": "RADHIKA EXPRESS", "uniqueVehicleCount": 3},
        {"Transporter": "E.AMALA", "uniqueVehicleCount": 1},
        {"Transporter": "GOVIND KALE", "uniqueVehicleCount": 3},
        {"Transporter": "PIYUSH TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "ISMAIL KHAN", "uniqueVehicleCount": 2},
        {"Transporter": "J SATHISH", "uniqueVehicleCount": 1},
        {"Transporter": "SABIR ULLA KHAN", "uniqueVehicleCount": 2},
        {"Transporter": "KAMLESH K. MEHTA", "uniqueVehicleCount": 4},
        {"Transporter": "SHIV OM SAI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "MAA KHODAL TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "JANHAVI TRANSPORT SERVICES", "uniqueVehicleCount": 2},
        {"Transporter": "ANIL R MAKARAND", "uniqueVehicleCount": 1},
        {"Transporter": "ARCHANA PANDEY", "uniqueVehicleCount": 4},
        {"Transporter": "OM TEMPO SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "SOMAYA MULTI SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "DUMMYTEST1", "uniqueVehicleCount": 1},
        {"Transporter": "VASILA ROADWAYS", "uniqueVehicleCount": 2},
        {"Transporter": "MUNDHE TRANSPORT", "uniqueVehicleCount": 5},
        {"Transporter": "NETAJI ARJUN NAIK", "uniqueVehicleCount": 1},
        {"Transporter": "MUNISHAMI GOWDA G N ", "uniqueVehicleCount": 2},
        {"Transporter": "VISHNU TRAVELS", "uniqueVehicleCount": 13},
        {"Transporter": "S.K. TOUR & TRAVEL", "uniqueVehicleCount": 3},
        {"Transporter": "PIYUSH GOODS CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "KGN TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "RAM PRAVESH SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "MOHAMMED KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "RANJIT SINGH", "uniqueVehicleCount": 1},
        {"Transporter": "RATANLAL SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "MEGHA ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "SATVIR KISHABSING VALMIKI", "uniqueVehicleCount": 1},
        {"Transporter": "SUMIT SOLANKI", "uniqueVehicleCount": 4},
        {"Transporter": "BANDENAVAZ", "uniqueVehicleCount": 1},
        {"Transporter": "AMARJEET", "uniqueVehicleCount": 1},
        {"Transporter": "SEEMA TRANSPORTER AND CONTRACTOR", "uniqueVehicleCount": 1},
        {"Transporter": "AMARJOT SINGH", "uniqueVehicleCount": 2},
        {"Transporter": "VANDANA TEMPO SER", "uniqueVehicleCount": 3},
        {"Transporter": "AJAY KRISHNPAL SHUKLA", "uniqueVehicleCount": 2},
        {"Transporter": "SUBHASH LALJI YADAV", "uniqueVehicleCount": 1},
        {"Transporter": "AISHWARRY TRANS.", "uniqueVehicleCount": 9},
        {"Transporter": "SAKEEL KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "SHRI ENTER", "uniqueVehicleCount": 1},
        {"Transporter": "SHAHAJI LAXMAN TAKLE", "uniqueVehicleCount": 1},
        {"Transporter": "SRI VAISHNAVI ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "J PRASADA RAO", "uniqueVehicleCount": 1},
        {"Transporter": "R.RAMESH KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "SEEMA", "uniqueVehicleCount": 1},
        {"Transporter": "Shiv Shakti Transport Services", "uniqueVehicleCount": 1},
        {"Transporter": "NISCHAL TYAGI", "uniqueVehicleCount": 1},
        {"Transporter": "ROHIT KUMAR", "uniqueVehicleCount": 3},
        {"Transporter": "PERFECT LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "PATLIPUTRALOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "TEN LOGISTICS INDIA PVT. LTD.", "uniqueVehicleCount": 4},
        {"Transporter": "CHIRAG LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "GURU CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "SEEMA TRANSPORT & CONTRACTOR", "uniqueVehicleCount": 5},
        {"Transporter": "AYYAPPA ENTERPRISES", "uniqueVehicleCount": 3},
        {"Transporter": "DP SHARMA", "uniqueVehicleCount": 3},
        {"Transporter": "ASIR AHMED PATHAN", "uniqueVehicleCount": 1},
        {"Transporter": "DILSHAD TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "NAVNATH HULAWLE", "uniqueVehicleCount": 3},
        {"Transporter": "S IBRAHIM", "uniqueVehicleCount": 1},
        {"Transporter": "ARAVIND ENETRPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "MOHAN KUMARA", "uniqueVehicleCount": 1},
        {"Transporter": "Khushi Enterprises", "uniqueVehicleCount": 1},
        {"Transporter": "MURTHY H R", "uniqueVehicleCount": 1},
        {"Transporter": "SENORITA TOUR & TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "", "uniqueVehicleCount": 1549},
        {"Transporter": "SKJ CASH CONTRACTOR", "uniqueVehicleCount": 21},
        {"Transporter": "SAI TRADE CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "SHRI SADGURU KIRPA TRAVELS", "uniqueVehicleCount": 3},
        {"Transporter": "JADHAV VIRAJ MAHADEV", "uniqueVehicleCount": 1},
        {"Transporter": "SUBHASH D. JAT", "uniqueVehicleCount": 1},
        {"Transporter": " VAISHNAVI TOUR & TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "MOHAMMED ZAKEY YUNUS KITTUR", "uniqueVehicleCount": 1},
        {"Transporter": "R.s.m. Drive Logistics", "uniqueVehicleCount": 1},
        {"Transporter": "MONIKA", "uniqueVehicleCount": 2},
        {"Transporter": "Raghavendra enterprises", "uniqueVehicleCount": 1},
        {"Transporter": "SHAILESH GADAM", "uniqueVehicleCount": 1},
        {"Transporter": "SAJITH", "uniqueVehicleCount": 1},
        {"Transporter": "SHANU", "uniqueVehicleCount": 1},
        {"Transporter": "SAWANT TRANSPORT SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "NEW RADHIKA TRANSPORT SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "Sonu Malik", "uniqueVehicleCount": 1},
        {"Transporter": "VIJAYALAKSHMI TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "CENTURY CARGO CARRIER PVT.LTD", "uniqueVehicleCount": 1},
        {"Transporter": "NEELAM RAM SINGH", "uniqueVehicleCount": 2},
        {"Transporter": "KULDEEP SINGH THAKUR LOGISTICS PVT.LTD.", "uniqueVehicleCount": 3},
        {"Transporter": "AKHILESH TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "NARASIMHAMURTHY K", "uniqueVehicleCount": 1},
        {"Transporter": "DEEPAKKUMARDUBEY", "uniqueVehicleCount": 2},
        {"Transporter": "M.ARUMUGAM", "uniqueVehicleCount": 2},
        {"Transporter": "SARA ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "SATYAWAN KHANDU KASBE", "uniqueVehicleCount": 1},
        {"Transporter": "SOLANKI RAJESHBHAI DHANJIBHAI", "uniqueVehicleCount": 1},
        {"Transporter": "ALNKAR TEMPO SERV", "uniqueVehicleCount": 6},
        {"Transporter": "SANI SUNIL LONDHE", "uniqueVehicleCount": 1},
        {"Transporter": "PRAHLAD SONWANE", "uniqueVehicleCount": 1},
        {"Transporter": "MANOHAR AUTO WORKS", "uniqueVehicleCount": 2},
        {"Transporter": "SAI VINGESH TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "R.R.ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "SOMAYA ROADLINES", "uniqueVehicleCount": 2},
        {"Transporter": "PAL TOURIEST", "uniqueVehicleCount": 1},
        {"Transporter": "SURESH LALJI YADAV", "uniqueVehicleCount": 3},
        {"Transporter": "SUBHASH VITTHAL MORE", "uniqueVehicleCount": 1},
        {"Transporter": "G KAVYA", "uniqueVehicleCount": 4},
        {"Transporter": "SHREE G.K.FREIGHT CARRIER", "uniqueVehicleCount": 1},
        {"Transporter": "RAGOTHUMAN", "uniqueVehicleCount": 2},
        {"Transporter": "ASHWIN LOURDES FERNANDES", "uniqueVehicleCount": 1},
        {"Transporter": "TEKNOLOGIKOL LOGISTICS PRIVATE LIMITED", "uniqueVehicleCount": 3},
        {"Transporter": "SHANTI TPT", "uniqueVehicleCount": 1},
        {"Transporter": "PUNEETA YADHAV", "uniqueVehicleCount": 2},
        {"Transporter": "STC TRANS LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SHITAL AMOL VALEKAR", "uniqueVehicleCount": 1},
        {"Transporter": "K SHOBHA RANI", "uniqueVehicleCount": 1},
        {"Transporter": "RESMA BANU", "uniqueVehicleCount": 1},
        {"Transporter": "ANAND RAMAKANT GHANEKAR", "uniqueVehicleCount": 1},
        {"Transporter": "SACHIN BHARATE", "uniqueVehicleCount": 2},
        {"Transporter": "HITESH LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "BALRAM SHARMA", "uniqueVehicleCount": 2},
        {"Transporter": "SURESH PATIL", "uniqueVehicleCount": 2},
        {"Transporter": "Maa Wheels Safe Services", "uniqueVehicleCount": 4},
        {"Transporter": "Jetex", "uniqueVehicleCount": 12},
        {"Transporter": "SURENDER SINGH TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "DELHI CASH CONTRACTORS", "uniqueVehicleCount": 10},
        {"Transporter": "RAJA SINGH G", "uniqueVehicleCount": 1},
        {"Transporter": "SHREE KALUBAI TRANSPORT SERVICE", "uniqueVehicleCount": 2},
        {"Transporter": "MOHAN RAJARAM RAUNDE", "uniqueVehicleCount": 1},
        {"Transporter": "DILIP JANGAL AWHALE", "uniqueVehicleCount": 1},
        {"Transporter": "Samadhan patil", "uniqueVehicleCount": 1},
        {"Transporter": "KALPESH GANESH MHATRE", "uniqueVehicleCount": 1},
        {"Transporter": "O CHANDRANNA", "uniqueVehicleCount": 2},
        {"Transporter": "M.RASOOL ALAUDEEN", "uniqueVehicleCount": 1},
        {"Transporter": "MANISH GOND", "uniqueVehicleCount": 1},
        {"Transporter": "CHANDRASHEKAR C M", "uniqueVehicleCount": 1},
        {"Transporter": "TIRUPADMA TRANSPORT CORPORATION", "uniqueVehicleCount": 1},
        {"Transporter": "SHRADDHA ROAD LINES", "uniqueVehicleCount": 1},
        {"Transporter": "TAPAN BARMAN", "uniqueVehicleCount": 2},
        {"Transporter": "BASKAR CHANDRASEKAR", "uniqueVehicleCount": 1},
        {"Transporter": "ASHU GULIA", "uniqueVehicleCount": 8},
        {"Transporter": "JESBON ANTONY", "uniqueVehicleCount": 3},
        {"Transporter": "ARMAAN ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "ADITI TRANSPORT SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "NARESH RAGHU LOHAT", "uniqueVehicleCount": 2},
        {"Transporter": "RAMA M MENDHEKAR", "uniqueVehicleCount": 2},
        {"Transporter": "DASHMESH TRANSPORTS", "uniqueVehicleCount": 1},
        {"Transporter": "A.P.R.LAXSHMI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "KG ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "HITESHBHAI RAMUBHAI AHIR", "uniqueVehicleCount": 1},
        {"Transporter": "MARUAAI TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "SAI TOUR AND TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "JALINDER SHIVAJI KAITKE ", "uniqueVehicleCount": 3},
        {"Transporter": "SANTOSH RAWAT", "uniqueVehicleCount": 2},
        {"Transporter": "MAHENDRA SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "I B SERVICES", "uniqueVehicleCount": 2},
        {"Transporter": "JAGBIR", "uniqueVehicleCount": 4},
        {"Transporter": "ZAST LOGISOLUTIONS PVT. LTD.", "uniqueVehicleCount": 1},
        {"Transporter": "NITIN GANPAT PATIL", "uniqueVehicleCount": 1},
        {"Transporter": "SAYYAD AFFROJUNNISA BEGUM", "uniqueVehicleCount": 1},
        {"Transporter": "SHIVAJI ABHIMAN PATIL", "uniqueVehicleCount": 1},
        {"Transporter": "SWIFT LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "BANSI TOURS AND TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "MUKESH KUMAR", "uniqueVehicleCount": 7},
        {"Transporter": "SRI SUBRAMANYAM TRANSPORTS", "uniqueVehicleCount": 3},
        {"Transporter": "RAGHUNATHSINGH B CHOUDHARY", "uniqueVehicleCount": 2},
        {"Transporter": "SHREE SAINATH ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "UMESHA C H", "uniqueVehicleCount": 3},
        {"Transporter": "ASHISH DATTATRAY ZENDE ", "uniqueVehicleCount": 1},
        {"Transporter": "K.P. ASWIN ", "uniqueVehicleCount": 1},
        {"Transporter": "SUDHA ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "KARAN TRANSPORT COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "SACHIN RAGHUNATH KAMBLE ", "uniqueVehicleCount": 1},
        {"Transporter": "A S TRANSPORT SERVICE              ", "uniqueVehicleCount": 1},
        {"Transporter": "PRASHANT BHARAT GOSWAMI", "uniqueVehicleCount": 1},
        {"Transporter": "AYAAN TRANSPORT", "uniqueVehicleCount": 9},
        {"Transporter": "A.VANITHA", "uniqueVehicleCount": 1},
        {"Transporter": "GKAVYATRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "PRASHANT GUPTA", "uniqueVehicleCount": 1},
        {"Transporter": "SHRIRAM TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "V GOPAL REDDY", "uniqueVehicleCount": 3},
        {"Transporter": "SRISTHI ENTERPRISES", "uniqueVehicleCount": 2},
        {"Transporter": "GAJENDRA V", "uniqueVehicleCount": 2},
        {"Transporter": "BHARAT GANAPATI MHADGUT", "uniqueVehicleCount": 1},
        {"Transporter": "MADHU.H.E", "uniqueVehicleCount": 1},
        {"Transporter": "ABHINAV ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "RAVI PRAKASH", "uniqueVehicleCount": 4},
        {"Transporter": "SUNIL TRANSPORT CO", "uniqueVehicleCount": 2},
        {"Transporter": "G STAR", "uniqueVehicleCount": 1},
        {"Transporter": "ANIL KISAN HARGUDE", "uniqueVehicleCount": 1},
        {"Transporter": "SHRI KRISHNA TRANSPORT CORP.", "uniqueVehicleCount": 1},
        {"Transporter": "SIDHARTH & COMPANY", "uniqueVehicleCount": 1},
        {"Transporter": "NAAZ CARGO CARRIERS", "uniqueVehicleCount": 1},
        {"Transporter": "YOGESH KISAN MORE", "uniqueVehicleCount": 1},
        {"Transporter": "APARNA TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "BHERU VAN CHUNA VAN", "uniqueVehicleCount": 1},
        {"Transporter": "SAQUIB R ZAIDI", "uniqueVehicleCount": 1},
        {"Transporter": "MANGALMURTI TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "RAM SREEPATEE GHARE", "uniqueVehicleCount": 2},
        {"Transporter": "A V LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SRI VENKATESWARA TRAVELS & LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "BHISE TRANSPORT SERVICES", "uniqueVehicleCount": 6},
        {"Transporter": "MANGESH TEMPO SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "MAA JIVDHANI TEMPO SERVICE", "uniqueVehicleCount": 3},
        {"Transporter": "ISMAIL KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "RAOSAHEB LAXMAN BANDGAR", "uniqueVehicleCount": 6},
        {"Transporter": "JEEVAN  MINI TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "SANTHOSH ENGINEERING", "uniqueVehicleCount": 2},
        {"Transporter": "Ragam Ramesh", "uniqueVehicleCount": 1},
        {"Transporter": "AJAY SEGHAL", "uniqueVehicleCount": 1},
        {"Transporter": "SHELUMATA TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "GIRIJA TRANSPORT & TRAVELS", "uniqueVehicleCount": 1},
        {"Transporter": "G SELVAM TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "RAMESH B", "uniqueVehicleCount": 1},
        {"Transporter": "AMAR ANANDA DAS", "uniqueVehicleCount": 2},
        {"Transporter": "DADAPEER", "uniqueVehicleCount": 3},
        {"Transporter": "K GNANAVELU", "uniqueVehicleCount": 1},
        {"Transporter": "A.M.GHANCHI", "uniqueVehicleCount": 1},
        {"Transporter": "HARISH B AHIR", "uniqueVehicleCount": 1},
        {"Transporter": "AMARJOT SINGH BINDRA", "uniqueVehicleCount": 2},
        {"Transporter": "ARINDAM COURIER SERVICE", "uniqueVehicleCount": 5},
        {"Transporter": "DCP LOGISTICS", "uniqueVehicleCount": 2},
        {"Transporter": "SHREE SHYAM TRANSPORT", "uniqueVehicleCount": 3},
        {"Transporter": "LAXMAN M. WAGHMARE", "uniqueVehicleCount": 1},
        {"Transporter": "VIJAY JAGDHANE", "uniqueVehicleCount": 1},
        {"Transporter": "P JEGAN", "uniqueVehicleCount": 1},
        {"Transporter": "Delhi Vapi Roadlines", "uniqueVehicleCount": 1},
        {"Transporter": "HIMANSHU MEHTA", "uniqueVehicleCount": 5},
        {"Transporter": "MANISH KUMAR", "uniqueVehicleCount": 8},
        {"Transporter": "AKBARBHAI VALIBHAI GHANCHI", "uniqueVehicleCount": 6},
        {"Transporter": "NEELAKANTAPPA B A", "uniqueVehicleCount": 6},
        {"Transporter": "D K TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "NSM ROADWAYS", "uniqueVehicleCount": 1},
        {"Transporter": "D.SRINIVASAN", "uniqueVehicleCount": 1},
        {"Transporter": "MAA KHARAKHAI LOGISTICS", "uniqueVehicleCount": 1},
        {"Transporter": "SUMESH ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "SRI SAIRAM TRANSPORT", "uniqueVehicleCount": 1},
        {"Transporter": "CHANDER SHEKHAR TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "RAMESHBHAI KHETABHAI ADGARA", "uniqueVehicleCount": 2},
        {"Transporter": "BARAMATIKAR NANDKUMAR R", "uniqueVehicleCount": 1},
        {"Transporter": "Amar Ananda Das", "uniqueVehicleCount": 2},
        {"Transporter": "JYOTI ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "ANKITA TOUR AND TRAVELS", "uniqueVehicleCount": 24},
        {"Transporter": "SHREE DEV JOM TARNSPORT", "uniqueVehicleCount": 7},
        {"Transporter": "AKHILESH KUMAR", "uniqueVehicleCount": 7},
        {"Transporter": "SATYAM MORESHWARAM TRANSPORT", "uniqueVehicleCount": 2},
        {"Transporter": "RANGANATHAN P", "uniqueVehicleCount": 4},
        {"Transporter": "PRIORITY COURIER SERVICE ", "uniqueVehicleCount": 3},
        {"Transporter": "SOGARATH LOGISTICS PRIVATE LIMITED", "uniqueVehicleCount": 5},
        {"Transporter": "TRANSHIP UTILITY SERVICE", "uniqueVehicleCount": 6},
        {"Transporter": "SURESH CHANDER SHARMA", "uniqueVehicleCount": 1},
        {"Transporter": "GULIA ENTERPRISES", "uniqueVehicleCount": 1},
        {"Transporter": "DILIP JAYRAM DEVARE", "uniqueVehicleCount": 3},
        {"Transporter": "KARAN LOGISTICS", "uniqueVehicleCount": 3},
        {"Transporter": "MISHRI TRANSPORT SERVICES", "uniqueVehicleCount": 3},
        {"Transporter": "E.ARUMAINATHAN", "uniqueVehicleCount": 2},
        {"Transporter": "JAGDISH KUMAR", "uniqueVehicleCount": 1},
        {"Transporter": "HARE KRISHANA TRANSPORT SERVICE", "uniqueVehicleCount": 1},
        {"Transporter": "CHAND PASHA AHMED HUSSAIN DUMDE", "uniqueVehicleCount": 1},
        {"Transporter": "NEW HORIZONS", "uniqueVehicleCount": 1},
        {"Transporter": "DC TRANSPORT", "uniqueVehicleCount": 4},
        {"Transporter": "NARINDER SHYAM", "uniqueVehicleCount": 1},
        {"Transporter": "RADHEY TEMPO TPT SERVICES", "uniqueVehicleCount": 4},
        {"Transporter": "RASHID KHAN AUTO SERVICES", "uniqueVehicleCount": 3},
        {"Transporter": "HG LOGISTICS", "uniqueVehicleCount": 4},
        {"Transporter": "ARNA TRANSPORT SERVICES", "uniqueVehicleCount": 1},
        {"Transporter": "SHAILESH MAHABALE", "uniqueVehicleCount": 5},
        {"Transporter": "ISLAMA KHAN", "uniqueVehicleCount": 2},
        {"Transporter": "RAJEESH P R", "uniqueVehicleCount": 2},
        {"Transporter": "SHILPA B", "uniqueVehicleCount": 1},
        {"Transporter": "SUBHASH JAT", "uniqueVehicleCount": 2},
        {"Transporter": "K.PARAMESHWARI", "uniqueVehicleCount": 2},
        {"Transporter": "KAUSHAL KISHOR", "uniqueVehicleCount": 1},
        {"Transporter": "NANASO GORAD", "uniqueVehicleCount": 1},
        {"Transporter": "MUJEEB ULLA KHAN", "uniqueVehicleCount": 1},
        {"Transporter": "GAJENDER SINGH", "uniqueVehicleCount": 4},
        {"Transporter": "SHWETA BAPURAO MAHAJAN", "uniqueVehicleCount": 1},
        {"Transporter": "BLUE DART", "uniqueVehicleCount": 1},
        {"Transporter": "FASTTRACK", "uniqueVehicleCount": 3}
    ]
}

data = response["data"]
total_entries = len(data)
total_vehicles = sum(item["uniqueVehicleCount"] for item in data)

# Count valid named transporters
named_transporters = [item["Transporter"] for item in data if item["Transporter"] not in [None, ""]]
null_or_empty = [item for item in data if item["Transporter"] in [None, ""]]

print(f"Total entries: {total_entries}")
print(f"Total vehicle count across all entries: {total_vehicles}")
print(f"Named transporter entries: {len(named_transporters)}")
print(f"Null or empty transporter entries count: {len(null_or_empty)}")
for item in null_or_empty:
    print(f"  - Null/empty item: {item}")
